### PR TITLE
Feature/ask for reviews

### PR DESCRIPTION
**Pull request by alexpdraper**
As per issue #40 

Adds a new reading list item asking for reviews when the list is rendered if we haven’t asked for reviews yet and if the person has 6+ items on the reading list.

### CODE REVIEW

**Comment by whitecat** [comment]
I like it I will accept after the changes are addressed.

**Comment by alexpdraper** [comment]
What changes?

**Comment by whitecat** [comment]
Why was new line at the end of `src/style/base/reading-item.styl` was removed.

Also why was `package-lock` checked in? There are [arguments for and against it](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5).  I do not see why it is important to us if we are not creating an npm registry.

**Comment by alexpdraper** [comment]
There were two new lines at the end of that file. And my editor makes it one new line when I save. Two is too many. Also, package-lock has been in the repo for an age. There was a change to it, so I checked in the change.

**Pull request merged**
