### PR TITLE
A bunch of features

### PR DESCRIPTION
**Pull request by lepirata**
I finally implemented all the features I wanted and merged everything into my master. 
This pull request includes:
- A sidebar in Firefox (#77)
- Custom drag & drop sorting (#56)
- A compact style with expandable reading items (#55)
- Reading item count in the icon badge (#63)
- Change icon when the active tab's page is in the reading list

And I think I'm done, I have all the features I needed. Now I can go and save my pages to read later as it should be.

### CODE REVIEW

**Comment by whitecat** [comment]
Thank you for your commits.

**Comment by whitecat** [comment]
What are the updates compared to the other commit you made? I would like to identify the changes.

**Comment by alexpdraper** [comment]
Much of this has already been merged with your previous pull request. Could you break this out into one pull request per feature?

**Comment by lepirata** [comment]
Yes, sorry about that, but keeping features separated it would have been too much work. This is an all or nothing deal, but I'm willing to do any change you need.

**Comment by whitecat** [comment]
@lepirata You have been doing a great job! We like all the features.

**Comment by alexpdraper** [comment]
This has become out of date.

**Pull request closed without merging**
